### ISSUE TITLE
Rails 6: DEPRECATION WARNING: Single arity template handlers are deprecated.

### ISSUE THREAD

**Issue by francesco-loreti** [cortiz/prawn-rails#37]
DEPRECATION WARNING: Single arity template handlers are deprecated.  Template handlers must
now accept two parameters, the view object and the source for the view object.
Change:
  >> Class#call(template)
To:
  >> Class#call(template, source)
 (called from <class:Engine> at C:/Ruby26-x64/lib/ruby/gems/2.6.0/gems/prawn-rails-1.2.0/lib/prawn-rails/engine.rb:8)

**Comment by westonganger** [comment]
Rails 6.0 has imlplemented a change that is incompatible with Temple at this time. Please see the relevant Issue and PR at the Temple repo page

Issue: https://github.com/judofyr/temple/issues/122
PR: https://github.com/judofyr/temple/pull/121

**Comment by mcgregordan** [comment]
Fixed in https://github.com/judofyr/temple/pull/121 and v0.8.1

**Comment by westonganger** [comment]
Temple fixed this and released a new version. Simply ensure you are running the latest version of `temple` and all will work as it should.

**Comment by alaarab** [comment]
Even when adding 'temple' to my Gemfile, I am still getting a deprecation warning:

DEPRECATION WARNING: Single arity template handlers are deprecated. Template handlers must
now accept two parameters, the view object and the source for the view object.
Change:
  >> PrawnRails::Renderer.call(template)
To:
  >> PrawnRails::Renderer.call(template, source)
